### ISSUE TITLE
Configure block headers to use Keccak256 instead of Blake2b

### ISSUE THREAD

**Issue by denalimarsh** [Snowfork/snowbridge#154]
The runtime-wide hash function is [configurable in the `frame_system` pallet](https://github.com/paritytech/substrate/blob/8783ce08f39ab7563d8c8af30ff1751f0c911a5e/frame/system/src/lib.rs#L196). So to create a standalone substrate chain, or a parachain it is possible to use `Keccak256`. This will simplify the verification process in Solidity as verifying a blake2b header against a hash is expensive.

See https://github.com/Snowfork/verification-solidity/pull/1#issuecomment-724149377.

**Comment by vgeddes** [comment]
@denalimarsh @philipstanislaus Is this required?

**Comment by musnit** [comment]
i think yes

**Comment by vgeddes** [comment]
Obsolete. Seems this was never required since our parachain is still using Blake256 while the beefy light client is working fine.
