### ISSUE TITLE
Relayer Operational Improvements

### ISSUE THREAD

**Issue by musnit** [Snowfork/snowbridge#190]
- Metrics/Logging/Dashboard
 - ...

**Comment by alistair-singh** [comment]
Trello write up.
https://trello.com/c/nj9cnvab/188-proper-logging-metrics-monitoring-dashboard-for-relayers-and-light-client-state-and-channel-state

**Comment by alistair-singh** [comment]
Current thinking on logging:
* Use a managed service like Elastic Cloud for ELK: https://www.elastic.co/cloud/
* We can ship nomad logs using a sidecar pattern. 
  * This will ship anything an nomad job writes to stdout/stderr.
  * https://learn.hashicorp.com/tutorials/nomad/jobs-accessing-logs#log-shipper-pattern
  * We can run Filebeat as a side car to ship logs into elastic. https://github.com/pagarme/docker-nomad-filebeat
* Logrus supports json formatting for logs which elastic understands natively.
  * We can add a command line flag that makes the relayers log out json formatter logs.
  * https://logz.io/blog/golang-logs/

**Comment by vgeddes** [comment]
Obsolete.
