### ISSUE TITLE
Upgrade to Solidity 0.8.0

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/snowbridge#213]
We should upgrade to Solidity 0.8.0 where ABIEncoderV2 is considered stable and is enabled by default.

Our ERC20 token contract depends on OpenZeppelin which doesn't yet support Solidity 0.8.0. So we need support mixed compiler versions. Truffle apparently doesn't allow this so we should consider migrating to Hardhat/Buidler.

**Comment by musnit** [comment]
this is done.
