### ISSUE TITLE
Untrusted parachain/pallet design

### ISSUE THREAD

**Issue by musnit** [Snowfork/snowbridge#220]
Currently, our trusted ETHApp/ERC20App smart contracts verify only that messages come from our trusted bridge. They do not verify that they come from a specific parachain/pallet. 

This is fine for now, as our bridge only has pallets with trusted code, but when we implement future support for XCM to Ethereum from untrusted parachains and/or pallets, we'll need to ensure our ETHApp/ERC20APP/trusted Ethereum smart contracts can protect against malicious parachains/pallets trying to pose as our Snowbridge Parachain pallets.

We'll also need a mechanism in general to let receiving smart contracts know which parachain and which application on that parachain a messages was sent from.

**Comment by vgeddes** [comment]
This ticket is now tracked in Linear: https://linear.app/snowfork/project/permissionless-channel-access-via-xcm-497a12662908/
