### ISSUE TITLE
Inbound channel and all our apps should verify message sender - internal audit/fixes todo

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/snowbridge#231]
need to check message.sender, still need to decide where best to do this:
 - either here in the channel (in which case, the App will need to register authorizedSenders, or have a method like getAuthorizedSenders, or somethin)
 - in the app (in which case we forward msg.sender into the app and let it check there)
 
I don't think it matters which for now, but longer term when we think about how we'll be supporting cross-parachain dispatch, this distinction may matter.

_Originally posted by @musnit in https://github.com/Snowfork/polkadot-ethereum/pull/223#discussion_r563042827_

**Comment by musnit** [comment]
To check - in Solidity, do we need to verify both the source channel that included the commitment as well as the source app that requested the commitment, or just the latter?

**Comment by philipstanislaus** [comment]
From #338: In `ethereum/contracts/ERC721App.sol:94`, ensure message sender is a known inbound channel

**Comment by vgeddes** [comment]
Resolving, this is all obsolete.
* Parachain inbound channels validate that incoming messages come from known Ethereum outbound channels.
* Parachain apps validate that messages (or calls later in the processing pipeline) are emitted by trusted Ethereum apps.
* Ethereum apps validate Ethereum inbound channels, and are configured with outbound channels at instantiation.
* Currently, our trusted set of core Ethereum apps are guaranteed that incoming messages originate from our Snowbridge parachain. They implicitly have to trust our parachain, since it is a core bridge component.
