### ISSUE TITLE
Future IncentivizedChannel Replay Protection Optimization

### ISSUE THREAD

**Issue by musnit** [Snowfork/snowbridge#251]
from https://github.com/Snowfork/polkadot-ethereum/pull/219#discussion_r566169369

For the IncentivizedChannel, replay protection is done with nonce-per-message. As we require and expect all commitments to  be processed by the channel in order, we can just do nonce-per-commitment for some minor gas savings.

**Comment by vgeddes** [comment]
implemented, resolving
