### ISSUE TITLE
Merkle Trie generation in basic channel is unbounded

### ISSUE THREAD

**Issue by alvatar** [Snowfork/snowbridge#305]
This could open potential DoS attacks by consuming all block weight.

**Comment by Rizziepit** [comment]
@alvatar can you point to the code you're referring to?

**Comment by musnit** [comment]
@Rizziepit This is related to https://github.com/Snowfork/polkadot-ethereum/pull/339 in which we are adding merkle-trie based commitments to the basic channel to be able to open it up to anyone in future. For the current version/launch it will stay permissioned and use flat commitments and so this issue will not be relevant until such point when we merge in that PR.

**Comment by vgeddes** [comment]
Obsolete, since #339 has been in stasis for quite a while, and will likely need to be redeveloped.
