### ISSUE TITLE
Integrate pallet-membership benchmarks once they're ready

### ISSUE THREAD

**Issue by Rizziepit** [Snowfork/snowbridge#383]
We started using the membership pallet in https://github.com/Snowfork/polkadot-ethereum/pull/348. Right now all weights are hardcoded to 50_000_000 but https://github.com/paritytech/substrate/pull/8596 added benchmarks. Once the benchmarks' generated `WeightInfo` is integrated into the pallet, we should update our Substrate version and add the benchmarks to our runtime.

**Comment by musnit** [comment]
Note: The current weights are over-weighted and so this is not really a security or major issue, but once the weights are updated by substrate or other dependencies, it could be valuable to update those in our parachain too for cheaper/more optimized costs.

**Comment by Rizziepit** [comment]
@musnit I had a look at the weight breakdown [here](https://github.com/paritytech/substrate/blob/master/frame/membership/src/weights.rs) and realized they're not actually over-weighted. Definitely not all of them. So I'm adding the security label here.

**Comment by vgeddes** [comment]
Obsolete. We've got weights in place now for this pallet.
