### ISSUE TITLE
Gas Optimization Audit

### ISSUE THREAD

**Issue by musnit** [Snowfork/snowbridge#412]

**Comment by vgeddes** [comment]
One example, here we increment the nonce (global storage) for each and every message in a single commitment. So if we have 10 messages in a commitment, that's 10 storage writes: https://github.com/Snowfork/polkadot-ethereum/blob/nomad/ethereum/contracts/BasicInboundChannel.sol#L95

Not sure if Ethereum cache's multiple writes to a single storage item in the scope of a single function.

**Comment by vgeddes** [comment]
Another example: The application contracts all store the channel addresses in storage. So referencing those addresses incurs a storage read. We can make use of the [singleton pattern](https://eips.ethereum.org/EIPS/eip-2470) so that the addresses are simply compile-time constants.

**Comment by musnit** [comment]
@vgeddes thanks these look good, though i suspect they are both minor/only on the long tail of optimizations. we should get some metrics and focus on the biggest inefficiencies first.

**Comment by vgeddes** [comment]
Obsolete. We're tracking this stuff in Linear now.
