### ISSUE TITLE
e2e tests doesn't work, relayer killed

### ISSUE THREAD

**Issue by rigidus** [Snowfork/snowbridge#456]
When I run e2e tests, I don't get the "System has been initialized" message as written at https://github.com/Snowfork/snowbridge/blob/main/test/README.md

Instead, I see a message stating that the relayer has been killed.

Here is the complete log: 

$ ./scripts/start-services.sh
./scripts/start-services.sh: line 10: kill: (147676) - No such process
Starting Ganache
wait-for-it.sh: waiting 32 seconds for localhost:8545
wait-for-it.sh: localhost:8545 is available after 0 seconds
Deploying contracts
~/src/bridge/snowbridge/ethereum ~/src/bridge/snowbridge/test

Compiling your contracts...
Everything is up to date, there is nothing to compile.

Network up to date.
Generating configuration from contracts
Using network 'e2e_test'.

~/src/bridge/snowbridge/test
Wrote configuration to /tmp/snowbridge-e2e-config
Building parachain and starting polkadot launch
~/src/bridge/snowbridge/parachain ~/src/bridge/snowbridge/test
    Finished release [optimized] target(s) in 1.02s
Generating Parachain spec
2021-07-14 13:53:08 Building chain spec
Inserting Ganache chain info into genesis spec
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1557    0  1473  100    84   479k  28000 --:--:-- --:--:-- --:--:--  506k
Writing Polkadot configuration
~/src/bridge/snowbridge/test
wait-for-it.sh: waiting 120 seconds for localhost:11144
2021-07-14 13:53:09  Building chain spec

🧹 Starting with a fresh authority set...
  👤 Added Genesis Authority alice
  👤 Added Genesis Authority bob

⛓ Adding Genesis Parachains
  ✓ Added Genesis Parachain 200
⛓ Adding Genesis HRMP Channels

2021-07-14 13:53:26  Building chain spec
2021-07-14 13:53:31  Took active validators from set with wrong size
2021-07-14 13:53:31  Took active validators from set with wrong size
Starting alice...
Added --enable-offchain-indexing=true,--offchain-worker=Always
Starting bob...
Added --enable-offchain-indexing=true,--offchain-worker=Always
2021-07-14 13:53:31          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:33          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:36          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:39          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:41          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:44          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:46          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:49          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-07-14 13:53:51          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
Starting a Collator for parachain 200: 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop, Collator port : 31200 wsPort : 11144
Added --alice
Added --chain=/tmp/snowbridge-e2e-config/spec.json
Added -lruntime=debug,--rpc-port=8081,--rpc-cors=all,--ws-external,--rpc-external,--rpc-methods=Unsafe,--offchain-worker=Always,--enable-offchain-indexing=true,--execution=native to parachain
Added --execution=wasm to collator
Starting a Collator for parachain 200: 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop, Collator port : 31201 wsPort : 11155
Added --bob
Added --chain=/tmp/snowbridge-e2e-config/spec.json
Added -lruntime=debug,--rpc-port=8082,--rpc-cors=all,--ws-external,--rpc-external,--rpc-methods=Unsafe,--offchain-worker=Always,--enable-offchain-indexing=true,--execution=native to parachain
Added --execution=wasm to collator
wait-for-it.sh: localhost:11144 is available after 76 seconds
Restarting Ganache with a slower block time
./scripts/start-services.sh: line 33: kill: (148563) - No such process
wait-for-it.sh: waiting 32 seconds for localhost:8545
wait-for-it.sh: localhost:8545 is available after 0 seconds
Waiting for consensus between polkadot and parachain
🚀 POLKADOT LAUNCH COMPLETE 🚀
Starting Relay
~/src/bridge/snowbridge/relayer ~/src/bridge/snowbridge/test
~/src/bridge/snowbridge/test
Relay PID: 149167
Process Tree:
bash─┬─artemis-relay───19*[{artemis-relay}]
     ├─node─┬─2*[artemis───75*[{artemis}]]
     │      ├─polkadot─┬─polkadot───17*[{polkadot}]
     │      │          ├─polkadot───21*[{polkadot}]
     │      │          └─69*[{polkadot}]
     │      ├─polkadot─┬─polkadot───17*[{polkadot}]
     │      │          ├─polkadot───21*[{polkadot}]
     │      │          └─71*[{polkadot}]
     │      └─10*[{node}]
     └─pstree
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
./scripts/start-services.sh: line 172: 149167 Killed                  build/artemis-relay run --config $configdir/config.toml > $logfile 2>&1  (wd: ~/src/bridge/snowbridge/relayer)
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.
Waiting for relayer to generate the DAG cache. This can take up to 20 minutes.

**Comment by rigidus** [comment]
I try to uncomment debug output in start_services.sh:138 and get it:


🚀 POLKADOT LAUNCH COMPLETE 🚀
Starting Relay
~/src/bridge/snowbridge/relayer ~/src/bridge/snowbridge/test
Using config file: /tmp/snowbridge-e2e-config/config.toml
INFO[0000] Creating worker                               worker=parachain-commitment-relayer
INFO[0000] Worker created                                worker=beefy-relayer
DEBU[0000] Starting worker                               restarts=0 source=WorkerPool worker=eth-relayer
DEBU[0000] Starting worker                               restarts=0 source=WorkerPool worker=parachain-commitment-relayer
INFO[0000] Starting worker                               worker=parachain-commitment-relayer
INFO[0000] 2021/07/14 14:34:13 Connecting to ws://127.0.0.1:11144/...  logger=stdlib
INFO[0000] Connected to chain                            chainID=344 endpoint="ws://localhost:8545/" worker=eth-relayer
INFO[0000] 2021/07/14 14:34:13 Connecting to ws://127.0.0.1:11144/...  logger=stdlib
INFO[0000] Connected to chain                            endpoint="ws://127.0.0.1:11144/" metaVersion=13 worker=parachain-commitment-relayer
INFO[0000] Connected to chain                            endpoint="ws://127.0.0.1:11144/" metaVersion=13 worker=eth-relayer
DEBU[0000] Retrieved finalized block number from parachain  blockNumber=30 worker=eth-relayer
Make the dag
INFO[0000] Connected to chain                            chainID=344 endpoint="ws://localhost:8545/" worker=parachain-commitment-relayer
INFO[0000] 2021/07/14 14:34:13 Connecting to ws://127.0.0.1:9944/...  logger=stdlib
INFO[0000] Connected to chain                            endpoint="ws://127.0.0.1:9944/" metaVersion=13 worker=parachain-commitment-relayer
INFO[0000] Starting Writer                               worker=parachain-commitment-relayer
INFO[0000] Starting Beefy Listener                       worker=parachain-commitment-relayer
ERRO[0000] Failed to get latest verified beefy block number from ethereum  error="no contract code at given address" worker=parachain-commitment-relayer
ERRO[0000] Failed to get latest relay chain block number and hash  error="no contract code at given address" worker=parachain-commitment-relayer
INFO[0000] Shutting down writer...                       worker=parachain-commitment-relayer
DEBU[0000] Starting worker                               restarts=0 source=WorkerPool worker=beefy-relayer
INFO[0000] Worker started                                worker=beefy-relayer
INFO[0000] Started database                              database=Beefy worker=beefy-relayer
INFO[0000] 2021/07/14 14:34:13 Connecting to ws://127.0.0.1:9944/...  logger=stdlib
INFO[0000] Connected to chain                            endpoint="ws://127.0.0.1:9944/" metaVersion=13 worker=beefy-relayer
INFO[0000] Connected to chain                            chainID=344 endpoint="ws://localhost:8545/" worker=beefy-relayer
INFO[0000] Shutting down database...                     database=Beefy worker=beefy-relayer
INFO[0000] Shutting down listener...                     worker=beefy-relayer
DEBU[0000] Worker terminated                             error="no contract code at given address" source=WorkerPool worker=beefy-relayer
ERRO[0010] The worker's goroutines are deadlocked. Please fix  source=WorkerPool worker=parachain-commitment-relayer
scripts/start-services.sh: line 126: 161490 Killed                  build/artemis-relay run --config $configdir/config.toml
scripts/start-services.sh: line 147: kill: (160828) - No such process
scripts/start-services.sh: line 148: kill: (161568) - No such process

**Comment by musnit** [comment]
The first time you run the relayeryou need to wait up to 2 hours for it to generate the dagcache  - issue is likely due to this. Did you do that and wait?
