### ISSUE TITLE
request publish permission

### ISSUE THREAD

**Issue by yrong** [Snowfork/snowbridge#459]
Hi Snowbridge,

  I've done some investigation in eth bridge related projects and add some notes in my [personal space](https://hackmd.io/LPSSzqi4QiyZMm4-qlNPBg) , I would like to publish the note to some public/semi public channels but not sure if it is proper with some codes attached extract from this repo, so  I would ask for permissions from you guys first

**Comment by musnit** [comment]
These notes look like they're mostly just a collection of parts copied from our existing documentation with a few personal additions.

If you think it would be helpful to include any suggestions or changes into our existing documentation, then feel free to make a pull request to them and we'll review and include them.

I'm not sure how you expect these notes to be consumed by others or where you would want to post them but again,

**Comment by yrong** [comment]
yes, it is more like a personal study note about the existing documentation, I add some background knowledge of beefy&mmr and why we need it also with some code comments about current implementation
