### ISSUE TITLE
hope some clarification about current design

### ISSUE THREAD

**Issue by yrong** [Snowfork/snowbridge#480]
Hi Snowfork team,

 First thanks for the open source project and great job you've done, much appreciated.  Recently I've read some of the docs/codes and still have some questions and look forward clarification from your team.

My understanding for the substrate->ethereum bridge there are 2 rounds of verification including:

1. [verify Relay Chain MMR roots signed by the correct set of Polkadot validators](https://github.com/Snowfork/snowbridge/blob/main/ethereum/contracts/BeefyLightClient.sol)

2. [uses Parachain Commitments to verify individual bridge messages]( https://github.com/Snowfork/snowbridge/blob/main/ethereum/contracts/ParachainLightClient.sol)

and for the first round of beefy verification we also need 2 phase commit

[newSignatureCommitment]( https://github.com/Snowfork/snowbridge/blob/5d2f0e183aaa561832f1daef3a91f2b8cf22fd40/ethereum/contracts/BeefyLightClient.sol#L192-L199)

[completeSignatureCommitment]( https://github.com/Snowfork/snowbridge/blob/5d2f0e183aaa561832f1daef3a91f2b8cf22fd40/ethereum/contracts/BeefyLightClient.sol#L289)

My question are:

1. since [beefy commitment](https://github.com/paritytech/grandpa-bridge-gadget/blob/e2beb88629df882ddd7b9c1e40b7c56aa1c9c505/beefy-gadget/src/worker.rs#L306-L317) already contains the required information such as mmr root and all signatures which we can verify easily in BeefyLightClient contract, will one step of SignatureCommitment  enough? what is the benifit of such 2 phase commit design?

2. from the current implementation seems [required SignatureCommitment](https://github.com/Snowfork/snowbridge/blob/5d2f0e183aaa561832f1daef3a91f2b8cf22fd40/ethereum/contracts/BeefyLightClient.sol#L415-L423) threshhold will be met only as [12%%](https://github.com/Snowfork/snowbridge/blob/5d2f0e183aaa561832f1daef3a91f2b8cf22fd40/ethereum/contracts/BeefyLightClient.sol#L129-L130), is that safe enough for the verification?

3. notice the incencitive channel charging from sender will pay for the honest worker, is there any punishment mechanism for the dishonest ones or just be unintentionally offline and fail it's duty?  could anyone run as relay worker?

**Comment by musnit** [comment]
1 - much cheaper
2 - yes, will be sharing docs on this in time
3 - it is not possible to be dishonest, the tx will be rejected if so. and yes anyone can run it

in future please feel free to ping us on our Element channel for general questions, rather than creating Github issues: https://matrix.to/#/%23snowbridge:matrix.org

**Comment by yrong** [comment]
@musnit  Get your point, first convert the initial signature array to some folded bit set array to save storage resource, and in second phase only sample some required signatures to save computing resource.  Really nice design!

  Btw, notice this [doc](https://snowbridge-docs.snowfork.com/concepts/polkadot-light-client-verifier/interactive-protocol) which may cover some details , but seems something wrong with the formula typesetting.

  Ok, I would seek help from element channel from now on. Thanks for your reply again.
