### ISSUE TITLE
Add tokenURI support to ERC721App

### ISSUE THREAD

**Issue by philipstanislaus** [Snowfork/snowbridge#500]
The ERC721App currently ignores the tokenURI of the NFT. Supporting the tokenURI requires SCALE encoding of arbitrary length strings on Ethereum. Arbitrary length strings require a compact SCALE encoded length prefix, which we don't have currently implemented.

_Originally posted by @musnit in https://github.com/Snowfork/snowbridge/pull/496#discussion_r691093432_

**Comment by vgeddes** [comment]
obsolete, NFT support is no longer in scope for our initial release
