### ISSUE TITLE
Handling fraudulent L1 Blocks

### ISSUE THREAD

**Issue by musnit** [Snowfork/snowbridge#523]
The bridge currently assumes that if a Proof of Work is correct, and is on the longest chain, then it contains a valid block. This should be a fairly safe assumption, given the high opportunity cost spent any attacker would have to pay to create fraudulent blocks that stay on the longest chain, especially with longer confirmation times.

Having said that, longer term as more light clients emerge in the space that also have this assumption, the bounty on this attack will go up and the assumption may break.

There are some efforts to build light clients that can also do full state-transition verification being explored. This ticket is being used to track them incase we explore this in future.

Optimistic Interactive Verification: https://github.com/geohot/cannon
ZK Verification: ...

**Comment by vgeddes** [comment]
Obsolete. The move to PoS changes the attack vectors significantly.
