### ISSUE TITLE
Update `snowbridge-ethereum` vulnerable dependency 

### ISSUE THREAD

**Issue by felixfaisal** [Snowfork/snowbridge#592]
Currently, `snowbridge-ethereum` makes use of `libsecp256k1 v0.3.5` which has a security issue
Refer to [bug report](https://rustsec.org/advisories/RUSTSEC-2021-0076)

**Recommendation**
Update `libsecp256k1` to a newer version 

Cargo audit output 
```
Crate:         libsecp256k1
Version:       0.3.5
Title:         libsecp256k1 allows overflowing signatures
Date:          2021-07-13
ID:            RUSTSEC-2021-0076
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0076
Solution:      Upgrade to >=0.5.0
```

**Comment by alistair-singh** [comment]
Thanks @felixfaisal . Will update the following dependencies.
https://github.com/Snowfork/snowbridge/blob/main/parachain/Cargo.lock#L4033-L4039

**Comment by alistair-singh** [comment]
PR Released: https://github.com/Snowfork/snowbridge/pull/596

**Comment by alistair-singh** [comment]
Dependency libsecp256k1 removed.
