### ISSUE TITLE
Meeting ERROR while executing command "yarn test"

### ISSUE THREAD

**Issue by roomdestroyer** [Snowfork/snowbridge#599]
Hey guys, in directory "snowbridge/ethereum", I ran command "yarn test" as given, most of the pacages were tested correctly, yet one error suddently occured, it looks like this: 
![image](https://user-images.githubusercontent.com/84266757/158496415-76b7d3b7-2a0a-4dbf-b5c1-377d82406c65.png)
The version of dependencies are like this:
![image](https://user-images.githubusercontent.com/84266757/158496466-7e5a9ff2-d882-491a-99d0-b96a5c029bca.png)

**Comment by roomdestroyer** [comment]
After a lot of effort, I still can't find any useful method to solve this error, could anyone help?

**Comment by roomdestroyer** [comment]
![image](https://user-images.githubusercontent.com/84266757/159041272-f9fb6774-5f7c-4f7c-82cb-c5c6751cf2d5.png)
The changing record is like this

**Comment by musnit** [comment]
@vgeddes thoughts?

**Comment by vgeddes** [comment]
Hey, the test in question was some stale code used to troubleshoot some beefy issues. I've removed it in https://github.com/Snowfork/snowbridge/pull/598.

**Comment by roomdestroyer** [comment]
> Hey, the test in question was some stale code used to troubleshoot some beefy issues. I've removed it in #598.

Thanks for your effort, I've re-cloned this part of code and it's test successfully.
