### ISSUE TITLE
An New Error visited while doing "yarn hardhat deploy --network ropsten"  in dir "ethereum"

### ISSUE THREAD

**Issue by roomdestroyer** [Snowfork/snowbridge#602]
Hey guys, I ran the command "yarn hardhat deploy --network ropsten" and this error occured:
![image](https://user-images.githubusercontent.com/84266757/159108261-2f2fa2d0-cd1c-4640-950e-654e4e980701.png)

But if I ran the command "yarn hardhat node" it worked successfully, how to resolve this error, and what's different about them?
![image](https://user-images.githubusercontent.com/84266757/159108363-cacd4bc2-9ab3-407b-a689-2abb51f33414.png)

**Comment by vgeddes** [comment]
Hey, snowbridge is still in development, and we aren't quite ready to provide general support for running our code. Stay tuned! We should be operational on Rococo in 1-3 months.
