### ISSUE TITLE
An error while doing "npx hardhat compile" in dir "/home/snowbridge/relayer"

### ISSUE THREAD

**Issue by roomdestroyer** [Snowfork/snowbridge#604]
This is the screeshot:
![image](https://user-images.githubusercontent.com/84266757/159109506-eaefc9ef-fb38-4c32-8e71-dd166628b230.png)
This is my environment:
![image](https://user-images.githubusercontent.com/84266757/159109558-085d48b8-22fe-47bd-8134-afd168f81872.png)
And before I had added the following config into file "relayer/.vscode/launch.json":
![image](https://user-images.githubusercontent.com/84266757/159109583-32851bde-e60e-4523-a78c-087e2883951d.png)

**Comment by vgeddes** [comment]
Hey, we aren't quite ready to provide general support. Snowbridge is still in development. We'll let the community know when we're ready.
