### ISSUE TITLE
Fees too expensive

### ISSUE THREAD

**Issue by gilescope** [Snowfork/snowbridge#615]
It's currently using identity fee for xcm:

type Trader = UsingComponents<IdentityFee<Balance>, RococoLocation, AccountId, Balances, ()>;

This is likely to mean the same fees as the relay chain. In all likelyhood parachains don't need as high fees.

https://github.com/paritytech/cumulus/issues/920 - we noticed this on statemint. Encointer have also recently tweaked their code to not use `IdentityFee<Balance>`. I suspect snowbridge wants to do the same.

**Comment by musnit** [comment]
Thanks! We're actually busy looking at fee structures for XCM at the moment - @vgeddes will you look into this/incorporate it into our XCM fee plans
