### ISSUE TITLE
Update Polkadot Dependencies for @snowfork/snowbridge-types

### ISSUE THREAD

**Issue by michaeldev5** [Snowfork/snowbridge#976]
Hi there,

I've encountered some unmet peer dependency warnings while using the @snowfork/snowbridge-types library, specifically related to the @polkadot/keyring library. Here's the error I'm encountering:

```
WARN  Issues with peer dependencies found
├─┬ @snowfork/snowbridge-types 0.2.7
│ └─┬ @polkadot/keyring 8.7.1
│ ├── ✕ unmet peer @polkadot/util@8.7.1: found 12.5.1 in @polkadot/apps-config
│ └── ✕ unmet peer @polkadot/util-crypto@8.7.1: found 12.5.1
```

Could you please take a look and consider updating the Polkadot dependencies for @snowfork/snowbridge-types?

Best regards,
Michael

**Comment by claravanstaden** [comment]
Hey @michaeldev5! Thanks for raising this. We are busy updating our Rust project to the latest [polkadot-sdk](https://github.com/paritytech/polkadot-sdk), will look at the JS dependencies too.

**Comment by alistair-singh** [comment]
The @snowfork/snowbridge-types package has been deprecated. Please use https://www.npmjs.com/package/@snowbridge/contract-types
